openapi: 3.0.0
info:
  title: online-code-executor-example
  description: API endpoint specification for online-code-executor-example
  version: 1.0.0
servers:
  - url: 'http://{host}:{port}'
    variables:
      host:
        default: localhost
      port:
        default: '3000'
    description: Development
tags:
  - name: dogs
    description: dogs
paths:
  /dogs:
    post:
      tags:
        - dogs
      summary: Save dog data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
      responses:
        '201':
          description: succeeded
        '405':
          description: validation failure
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
          nullable: false
        breed:
          type: string
          nullable: false
          minLength: 1
          maxLength: 256
        name:
          type: string
          nullabel: false
          minLength: 1
          maxLength: 256
